task_manager_app/config/routes.rb
Rails.application.routes.draw do
  devise_for :users 
  resources :projects
  resources :tasks
  

  root :to => "projects#index"
  
#  Peters-MacBook-Pro:task_manager_app PeterWinterhof$ rake routes
#                   Prefix Verb   URI Pattern                    Controller#Action
#                 projects GET    /projects(.:format)            projects#index
#                          POST   /projects(.:format)            projects#create
#              new_project GET    /projects/new(.:format)        projects#new
#             edit_project GET    /projects/:id/edit(.:format)   projects#edit
#                  project GET    /projects/:id(.:format)        projects#show
#                          PATCH  /projects/:id(.:format)        projects#update
#                          PUT    /projects/:id(.:format)        projects#update
#                          DELETE /projects/:id(.:format)        projects#destroy
#                    tasks GET    /tasks(.:format)               tasks#index
#                          POST   /tasks(.:format)               tasks#create
#                 new_task GET    /tasks/new(.:format)           tasks#new
#                edit_task GET    /tasks/:id/edit(.:format)      tasks#edit
#                     task GET    /tasks/:id(.:format)           tasks#show
#                          PATCH  /tasks/:id(.:format)           tasks#update
#                          PUT    /tasks/:id(.:format)           tasks#update
#                          DELETE /tasks/:id(.:format)           tasks#destroy
#         new_user_session GET    /users/sign_in(.:format)       devise/sessions#new
#             user_session POST   /users/sign_in(.:format)       devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)      devise/sessions#destroy
#            user_password POST   /users/password(.:format)      devise/passwords#create
#        new_user_password GET    /users/password/new(.:format)  devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format) devise/passwords#edit
#                          PATCH  /users/password(.:format)      devise/passwords#update
#                          PUT    /users/password(.:format)      devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)        devise/registrations#cancel
#        user_registration POST   /users(.:format)               devise/registrations#create
#    new_user_registration GET    /users/sign_up(.:format)       devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)          devise/registrations#edit
#                          PATCH  /users(.:format)               devise/registrations#update
#                          PUT    /users(.:format)               devise/registrations#update
#                          DELETE /users(.:format)               devise/registrations#destroy
# root GET    /                              projects#index

end

task_manager_app/app/models/project.rb
class Project < ActiveRecord::Base
	attr_accessor :name, :user_id
	belongs_to :user
	has_many :tasks
end

task_manager_app/app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :user
	belongs_to :project
end

task_manager_app/app/models/user.rb
class User < ActiveRecord::Base
	has_many :tasks, through: :projects
	has_many :projects
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

task_manager_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

task_manager_app/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
before_action :authenticate_user!
	def index
		@project = Project.all
		@current_user = current_user

	end
	def show
		
		@project = Project.find(params[:id])
		@task = Task.all
	end
	def create
		
		@project = Project.create(project_params)
		redirect_to '/'
	end
	def project_params
		params.permit(:project_name, :users_id)
	end
	def destroy
		@project = Project.find(params[:id])
    @project.destroy
    redirect_to '/'
   end


end

task_manager_app/app/controllers/tasks_controller.rb
class TasksController < ApplicationController

	def create
		@task = Task.create(task_params)
		
		@project = Project.find(params[:projects_id])
		redirect_to @project
	end

	def task_params
		params.permit(:name, :users_id, :projects_id, :completed)
	end
	def update
		@task=Task.find(params[:id])
		@task.update_attributes(completed: true)
		@project = Project.find(@task.projects_id)
		redirect_to @project
	end
	def destroy
		
		@task = Task.find(params[:id])
		@project = Project.find(@task.projects_id)
    @task.destroy
    redirect_to @project
  end
end

task_manager_app/app/helpers/application_helper.rb
module ApplicationHelper
end

task_manager_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TaskManagerApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <style type="text/css">
  #body-container{
      background: url("show_background.jpg") white;
      background-position: center;
      background-size:cover;
      position: fixed;
      height: 100%;
      width:100%;
      font-size: 20px;
    }
  
      
  
  background: url("background1.jpg") white;
  </style>
</head>
<body>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>

<%= yield %>

</body>
</html>

task_manager_app/app/views/projects/_form.html.erb
<%= form_for @project do |form| %>
  Create a new project: <%= form.text_field :name %></br>
  <%= form.hidden_field :user_id, :value => current_user.id %></br>
  <%= form.submit %>
<% end %>

task_manager_app/app/views/projects/index.html.erb
<head>
	<style type="text/css">
		.clicks{
			color:blue;
		}
		
		#body-container{
	      background: url("show_background.jpg") white;
	  		color:black;
	      background-position: center;
	      background-size:cover;
	      position: fixed;
	      height: 100%;
	      width:100%;
	      font-size: 20px;
	    }
		h1{
			text-align: center;
			color: white;
			text-decoration: underline;

		}
		#tasks-container{
			height:100%;
			background:rgba(0,0,0,0.5);
			
			position: center;
			width: 40%;
			height: 70%;
			margin-left: auto;
			margin-right: auto;
			border-radius: 25px;
			border-color: grey;
			border-width: 25px;
		}
		#form-container{
			position:relative;
			height: 100px;
			margin-left: auto;
			margin-right: auto;
			
			bottom:10%;
			left:32%;			
		}
	</style>
</head>
<body>
	<div id="body-container">
	<h1>Your Lists</h1>

		<div id="tasks-container">
		<% @project.each do |beta|%>
		    
		    <%if beta.users_id == current_user.id%>
		    </br>
		    <div>
		    <%= button_to beta.project_name, project_path(beta.id), :style=>'color: black; float:left', :method =>'get' %>
		    <%= button_to 'Delete List', beta, :method => 'delete', :style=>'float:right; color: black'%></br>
		    </div>
		    
		    <%end%> 
		<% end %>
		</div>
		
		<div id="form-container">
			<form accept-charset="UTF-8" action="/projects" method="post">
			  <%= token_tag %>
			  
			  <input type="text" name="project_name" id="name" style="width: 300px; left:40%"/>
			  <input type="hidden" name="users_id" id="users_id" value= '<%=current_user.id%>' />

			  <button type="submit">Create a New List</button>
			</form>
		
		</div>
	</div>
</body>

task_manager_app/app/views/projects/show.html.erb
<head>
	<style type="text/css">
		
		
		#body-container{
	      background: url("http://hdwgo.com/wp-content/uploads/2015/03/autumn-background-nature-wallpapers-images.jpg") white;

	      background-position: center;
	      background-size:cover;
	      position: fixed;
	      height: 100%;
	      width:100%;
	      font-size: 20px;
	    }
		h1{
			text-align: center;
			color:white;
			text-decoration: underline;
		}
		h2{
			font-size: 24px;
			text-align: center;
			color: white;
			text-decoration: underline;
		}
		#tasks-container{
			
			margin-left: auto;
			margin-right: auto;
			position: relative;
			height:80%;
			vertical-align: top;
			padding-left: 12%;
			padding-right: auto;
		}
		.tasks{
			height:100%;
			display: inline-block;
			background:rgba(0,0,0,0.5);
			
			position: relative;
			width: 40%;
			height: 80%;
			border-radius: 25px;
			border-color: grey;
			border-width: 25px;
			vertical-align: top;
			padding: 10px
		}
		
		#form-container{
			position:relative;
			height: 100px;
			margin-left: auto;
			margin-right: auto;
			
			bottom:10%;
			left:32%;			
		}
		

	</style>
</head>

<body>




	<div id="body-container">
	<%= button_to 'Back to Lists', { :action => "index" }, :method => :get %>
	<h1>Your Tasks for <%=@project.project_name%> List</h1>

	<div id="tasks-container">

		<article class="tasks">
			<h2>In Progress</h2>
			<% @task.each do |beta|%>
			    <%if beta.users_id == current_user.id && beta.projects_id == @project.id && beta.completed == false%>
			    </br>
			    <button style= "float:left" disabled ><%=beta.name%></button>
			    <%= button_to 'Task completed', beta, :method => 'patch', :style=>'float:right; color: black'%></br>
			    <%end%> 
			<% end %>
		</article>
		<article class="tasks">
			<h2>Completed</h2>
			<% @task.each do |beta|%>
			    <%if beta.users_id == current_user.id && beta.projects_id == @project.id && beta.completed == true%>
			    
			    </br>
			    <button disabled><%=beta.name%></button>
			    </br>
			    <%end%> 
			<% end %>
		</article>
	
	</div>

			<div id="form-container">
				<form accept-charset="UTF-8" action="/tasks" method="post">
				<%= token_tag %>
				  
				  <input type="text" name="name" id="name" style="width: 300px; left:40%"/>
				  <input type="hidden" name="users_id" id="users_id" value= '<%=current_user.id%>' />
				  <input type="hidden" name="completed" id="users_id" value= 'false' />
				  <input type="hidden" name="projects_id" id="projects_id" value= '<%=@project.id%>' />
				  
				  <button type="submit">Create New Task</button>
				</form>
			</div>
	</div>	
	
</body>